name: Daily Demand-Gen Digest

on:
  schedule:
    # run every day at 9:00 AM America/Chicago
    - cron:  '0 9 * * *'
  workflow_dispatch: {}

jobs:
  run-digest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install python-dotenv feedparser requests beautifulsoup4 openai

      - name: Run demand-gen agent
        env:
          DB_PATH:        ${{ secrets.DB_PATH }}
          SMTP_HOST:      ${{ secrets.SMTP_HOST }}
          SMTP_PORT:      ${{ secrets.SMTP_PORT }}
          SMTP_USER:      ${{ secrets.SMTP_USER }}
          SMTP_PASS:      ${{ secrets.SMTP_PASS }}
          EMAIL_FROM:     ${{ secrets.EMAIL_FROM }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python3 dgagent.py
